apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.configmap.metadata.name }}
data:
  MYSQL_HOST: {{ .Values.backend.configmap.data.mysqlhost }}
  DB_PORT: "{{ .Values.backend.configmap.data.mysqlport }}"
  MYSQL_USER: {{ .Values.backend.configmap.data.mysqluser }}
  MYSQL_ROOT_PASSWORD: {{ .Values.backend.configmap.data.mysqlpasswd }}
  MYSQL_DATABASE: {{ .Values.backend.configmap.data.mysqldb }}
