---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.meatadata.name }}-service
spec:
  selector:
    app: {{ .Values.frontend.spec.selector.matchLabels }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.serviceport }}
      targetPort: {{ .Values.frontend.spec.template.spec.containers.ports.containerport }}
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.metadata.name }}-service
spec:
  selector:
    app: {{ .Values.backend.spec.selector.matchLabels }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.configmap.data.serviceport }}
      targetPort: {{ .Values.backend.spec.template.spec.containers.ports.containerport }}
      nodePort: {{ .Values.backend.configmap.data.nodeport }}
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.metadata.name }}-service
spec:
  selector:
    app: {{ .Values.mysql.spec.selector.matchLabels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.serviceport}}
      targetPort: {{ .Values.mysql.spec.template.spec.containers.ports.containerport }}
  type: NodePort